### PR TITLE
Added test coverage command

### PR DESCRIPTION
**Pull request by cbouwense**
image

Run `npm run coverage` and check out `coverage/index.html` in your browser.

### CODE REVIEW

**Comment by cbouwense** [comment]
not sure why this would fail a build 🤔

**Comment by AlexMassenzio** [comment]
> not sure why this would fail a build 🤔

[09:08:17.328] Cloning github.com/AlexMassenzio/wordchain (Branch: guppy/test-coverage, Commit: d202d71)
[09:08:18.303] Cloning completed: 974.924ms
[09:08:19.141] Restored build cache
[09:08:19.195] Running "vercel build"
[09:08:19.855] Vercel CLI 28.6.0
[09:08:20.668] Detected `pnpm-lock.yaml` generated by pnpm 7...
[09:08:20.679] Installing dependencies...
[09:08:21.398] Lockfile is up to date, resolution step is skipped
[09:08:21.402]  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
[09:08:21.402] 
[09:08:21.402] Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
[09:08:21.426] Error: Command "pnpm install" exited with 1

**Comment by AlexMassenzio** [comment]
Looks like lock file wasnt included. Ill send it up

**Review by AlexMassenzio — APPROVED** [review]
Thanks for adding this boi

**Comment by cbouwense** [comment]
oh, interesting, not used to committing lock files, but that makes sense, ty boi

**Pull request merged**
