### PR TITLE
Added a bunch of Y words.

### PR DESCRIPTION
**Pull request by agincel**
If plural words aren't allowed, I'd still petition we keep 'yahoo', 'yikes', 'yappy', 'yummy', 'yucky', and 'yucca', but imo allowing plurals gives the Y section much more flexibility, even if that's generally an exception made for Y and other letters with smaller pools.

### CODE REVIEW

**Comment by AlexMassenzio** [comment]
Thanks for the PR! Yeah we don't currently use purals words, and we should probably remove the y words that end with y as well, since the goal is to balance out how many Ys are being picked.

**Review by AlexMassenzio — CHANGES_REQUESTED** [review]
We might want to not include purals and y*y words.

**Comment by agincel** [comment]
> 

Removed all y*y and y*s words with the exception of 'yikes' which I think merits consideration

**Comment by AlexMassenzio** [comment]
Merging into staging for build at midnight.

**Pull request merged**
